projectBuilding:

  markupProcessing:

    entryPointsGroups:

      StaticPreview:

        topDirectoryRelativePath: 01-Source/index.pug

        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: 03-ProductionBuild }


  plainCopying:

    filesGroups:

      BootstrapStyles:

#        sourceFileRelativePath: node_modules/bootstrap/dist/css/bootstrap.css
        sourceDirectoryRelativePath: node_modules/bootstrap/dist/css
        aliasName: Bootstrap
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild/styles
            filesRenamings:
              - pathRelativeToSourceDirectory: bootstrap-grid.min.css
                newFileNameWithExtension: BootstrapGrid.min.css

          PRODUCTION: { outputTopDirectoryRelativePath: 03-ProductionBuild/styles }

      Env:

        sourceFileRelativePath: 01-Source/.env
        referenceName: Env
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild/styles
            newFileNameWithExtension: ".env.local"
          PRODUCTION:
            outputTopDirectoryRelativePath: 03-ProductionBuild/styles
            newFileNameWithExtension: ".env.production"


  browserLiveReloading:

    setups:

      StaticPreview:

        localServer:
          rootDirectoryRelativePath: 02-LocalDevelopmentBuild
