$projectBuilding:

  $commonSettings:

    $publicDirectoriesRelativePaths:

      $production: ProductionBuilding


  $markupProcessing:

    $entryPointsGroups:

      All:

        $sourceFilesTopDirectoryRelativePath: Source

        $buildingModeDependent:
          $production:
            $outputTopDirectoryRelativePath: ProductionBuilding
