$projectBuilding:

  $commonSettings:

    $selectiveExecutions:

      StaticPreview:

        $tasksAndSourceFilesSelection:

          $markupProcessing: [ StaticPreview, Pages ]

      Application:

        $tasksAndSourceFilesSelection:

          $markupProcessing: [ SingePageApplicationEntryPoint ]


  $markupProcessing:

    $entryPointsGroups:

      StaticPreview:

        $singleEntryPointSourceFileRelativePath: 01-Source/StaticPreview/StaticPreviewAnywherePage.pug
        $buildingModeDependent:
          $staticPreview:
            $outputTopDirectoryRelativePath: 02-StaticPreviewBuild

      Pages:

        $sourceFilesTopDirectoryRelativePath: 01-Source/Pages
        $sourceFilesSelection:
          $prefixesOfExcludedSubdirectories: "_"
          $prefixesOfExcludeFiles: "_"

        $buildingModeDependent:
          $staticPreview:
            $outputTopDirectoryRelativePath: 02-StaticPreviewBuild
