/* ━━━ < Imports ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
/* ┅┅┅ Normalized Settings ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
import type ProjectBuildingCommonSettings__Normalized from
    "@ProjectBuilding/Common/NormalizedConfig/ProjectBuildingCommonSettings__Normalized";

/* ┅┅┅ Settings Representatives ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
import type ProjectBuildingMasterConfigRepresentative from "@ProjectBuilding/ProjectBuildingMasterConfigRepresentative";

/* ┅┅┅ Shared State ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
import CommonSharedState from "@ProjectBuilding/Common/CommonSharedState";

/* ┅┅┅ Vinyl FS ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
import type VinylFileClass from "@Utils/VinylFileClass";

/* ┅┅┅ Utils ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
import PostCSS from "postcss";
import type { HTMLElement } from "node-html-parser";
import parseSelectors, {
  type Processor as SelectorsProcessor,
  type ClassName as CSS_ClassNode,
  type Root as PostCSS_Root
} from "postcss-selector-parser";
import {
  isUndefined,
  isNotUndefined,
  lowercaseLatinCharacters,
  stringifiedDigits
} from "@yamato-daiwa/es-extensions";
/* ━━━ Imports > ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */


export default abstract class CSS_ClassesShortener {

  public static replaceAllowedCSS_ClassesInStylesheetAndSaveCorrespondencesIfMust(
    stylesheet: VinylFileClass,
    projectBuildingMasterConfigRepresentative: ProjectBuildingMasterConfigRepresentative
  ): void {

    const CSS_ClassesMinificationOnFlySettings: ProjectBuildingCommonSettings__Normalized.CSS_ClassesMinificationOnFly =
        projectBuildingMasterConfigRepresentative.CSS_ClassesMinificationOnFlySettings;

    if (!CSS_ClassesMinificationOnFlySettings.enabled) {
      return;
    }


    const {
      CSS_ClassesRegularExpressions,
      ignoredCSS_Classes,
      forbiddenMinifiedCSS_ClassesNames
    }: ProjectBuildingCommonSettings__Normalized.CSS_ClassesMinificationOnFly =
        projectBuildingMasterConfigRepresentative.CSS_ClassesMinificationOnFlySettings;

    const postCSS_Root: PostCSS.Root = PostCSS.parse(stylesheet.stringifiedContents);

    const parser: SelectorsProcessor<void> = parseSelectors(
      (processor: PostCSS_Root): void => {
        processor.walkClasses(
          (classNode: CSS_ClassNode): void => {

            CSS_ClassesShortener.processPostCSS_ClassNode({
              classNode,
              ignoredCSS_Classes,
              CSS_ClassesRegularExpressions,
              forbiddenMinifiedCSS_ClassesNames
            });

          }
        );
      }
    );

    postCSS_Root.walkRules(
      (rule: PostCSS.Rule): void => {
        rule.selector = parser.processSync(rule.selector);
      }
    );

    stylesheet.setContents(postCSS_Root.toString());

  }

  /* [ Approach ]
   * Initially, the replacing of CSS classes in markup has been executed by a separate class, but once the shortening
   *   of CSS classes not mentioned in stylesheets functionality has been added, the accessing to
   *   `issueAndNewAvailableCSS_ClassName` private method has become required. Of course, all short names of CSS
   *    classes must be generated by a single source for the consistency. */
  public static replaceAllowedCSS_ClassesInMarkupAndSaveCorrespondencesIfMust(
    rootElement: HTMLElement,
    projectBuildingMasterConfigRepresentative: ProjectBuildingMasterConfigRepresentative
  ): HTMLElement {

    if (
      !projectBuildingMasterConfigRepresentative.CSS_ClassesMinificationOnFlySettings.enabled ||
          CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence.size === 0
    ) {
      return rootElement;
    }


    const {
      generatingInMarkupOfShortCSS_ClassesNotMentionedInStylesheets,
      forbiddenMinifiedCSS_ClassesNames
    }: ProjectBuildingCommonSettings__Normalized.CSS_ClassesMinificationOnFly =
        projectBuildingMasterConfigRepresentative.CSS_ClassesMinificationOnFlySettings;

    for (const element of rootElement.querySelectorAll("[class]")) {

      const classAttributeInitialValue: string | undefined = element.getAttribute("class");

      if (isUndefined(classAttributeInitialValue)) {
        continue;
      }


      /* [ Specification ]
       * It is assumed that the limitations like forbidden CSS class names have been respected when filled
       *   `CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence`. */
      element.setAttribute(
        "class",
        classAttributeInitialValue.
            split(/\s+/u).
            map(
              (initialCSS_ClassName: string): string => {

                const preAssignedShortCSS_ClassName: string | undefined =
                  CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence.get(initialCSS_ClassName);

                if (isNotUndefined(preAssignedShortCSS_ClassName)) {
                  return preAssignedShortCSS_ClassName;
                }


                if (
                  !generatingInMarkupOfShortCSS_ClassesNotMentionedInStylesheets.enabled ||
                      generatingInMarkupOfShortCSS_ClassesNotMentionedInStylesheets.ignoredInitialCSS_Classes.
                          has(initialCSS_ClassName)
                ) {
                  return initialCSS_ClassName;
                }


                const newShortCSS_ClassName: string =
                    CSS_ClassesShortener.issueAndNewAvailableCSS_ClassName(forbiddenMinifiedCSS_ClassesNames);

                CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence.
                    set(initialCSS_ClassName, newShortCSS_ClassName);

                return newShortCSS_ClassName;

              }
            ).
            join(" ")
      );

    }


    return rootElement;

  }


  /* ━━━ Private Methods ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */
  private static processPostCSS_ClassNode(
    {
      classNode,
      ignoredCSS_Classes,
      CSS_ClassesRegularExpressions,
      forbiddenMinifiedCSS_ClassesNames
    }:
        Readonly<{ classNode: CSS_ClassNode; }> &
        Pick<
          ProjectBuildingCommonSettings__Normalized.CSS_ClassesMinificationOnFly,
            "ignoredCSS_Classes" |
            "CSS_ClassesRegularExpressions" |
            "forbiddenMinifiedCSS_ClassesNames"
        >
  ): void {

    const initialCSS_ClassName: string = classNode.value;

    if (
      ignoredCSS_Classes.has(initialCSS_ClassName) ||
          !Array.from(CSS_ClassesRegularExpressions).
              some(
                (regularExpression: RegExp): boolean =>
                    regularExpression.test(initialCSS_ClassName)
              )
    ) {
      return;
    }


    const assignedEarlierShortCSS_ClassName: string | undefined =
        CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence.get(initialCSS_ClassName);

    if (isUndefined(assignedEarlierShortCSS_ClassName)) {

      const newShortCSS_ClassName: string =
          CSS_ClassesShortener.issueAndNewAvailableCSS_ClassName(forbiddenMinifiedCSS_ClassesNames);

      CommonSharedState.initialAndShortenedCSS_ClassesCorrespondence.
          set(initialCSS_ClassName, newShortCSS_ClassName);

      classNode.value = newShortCSS_ClassName;

    } else {

      classNode.value = assignedEarlierShortCSS_ClassName;

    }

  }


  /* ┅┅┅ Issuing of Classes Names ┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅ */
  /* eslint-disable-next-line @typescript-eslint/member-ordering -- Used by the following methods only. */
  private static readonly indexesOfCharacters: Array<number> = [ 0, 0 ];

  private static issueAndNewAvailableCSS_ClassName(
    forbiddenMinifiedCSS_ClassesNames: ReadonlySet<string>
  ): string {

    let newShortCSS_ClassName: string;

    do {

      newShortCSS_ClassName = CSS_ClassesShortener.indexesOfCharacters.
          map(
            (characterIndexInSet: number, characterIndexInCSS_ClassName: number): string =>
                (
                  characterIndexInCSS_ClassName === CSS_ClassesShortener.indexesOfCharacters.length - 1 ?
                      stringifiedDigits : lowercaseLatinCharacters
                )[characterIndexInSet]
          ).
          join("");

      CSS_ClassesShortener.increment();

    } while (forbiddenMinifiedCSS_ClassesNames.has(newShortCSS_ClassName));

    return newShortCSS_ClassName;

  }

   private static increment(): void {

     const positionsCount: number = CSS_ClassesShortener.indexesOfCharacters.length;

     for (
       let characterPositionIndex: number = positionsCount - 1;
       characterPositionIndex >= 0;
       characterPositionIndex--
     ) {

       const targetCharactersSet: Array<string> =
           characterPositionIndex === positionsCount - 1 ?
               stringifiedDigits : lowercaseLatinCharacters;

       const indexOnCurrentCharacterInSet: number =
           CSS_ClassesShortener.indexesOfCharacters[characterPositionIndex];

       const indexOfNextCharacter: number =
           indexOnCurrentCharacterInSet === targetCharactersSet.length - 1 ?
               0 : indexOnCurrentCharacterInSet + 1;

       CSS_ClassesShortener.indexesOfCharacters[characterPositionIndex] = indexOfNextCharacter;

       if (indexOfNextCharacter !== 0) {
         return;
       }

     }

     CSS_ClassesShortener.indexesOfCharacters.unshift(0);

  }

}
