projectBuilding:

  markupProcessing:

    staticPreview:

      stateDependentPagesVariationsSpecificationFileRelativePath: 01-Source/StaticPreview/PagesStateDependentVariations.yaml

    entryPointsGroups:

      StaticPreview:

        singleEntryPointRelativePath: 01-Source/StaticPreview/StaticPreviewAnywherePage.pug

        buildingModeDependent:
          STATIC_PREVIEW:
            outputTopDirectoryRelativePath: 02-StaticPreviewBuild

      Pages:

        topDirectoryRelativePath: 01-Source/Pages
        partialsRecognition:
          excludeSubdirectoriesWithPrefixes: "_"
          excludeFilesWithPrefixes: "_"

        buildingModeDependent:
          STATIC_PREVIEW:
            outputTopDirectoryRelativePath: 02-StaticPreviewBuild
