projectBuilding:

  markupProcessing:

    entryPointsGroups:

      All:

        sourceFilesTopDirectoryRelativePath: 01-Source/Pages
        partialsRecognition:
          excludeSubdirectoriesWithNames: [ Partials ]

        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: 03-ProductionBuild }


  stylesProcessing:

    entryPointsGroups:

      All:

        sourceFilesTopDirectoryRelativePath: 01-Source/Pages
        partialsRecognition:
          excludeSubdirectoriesWithNames: [ Partials ]

        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: 03-ProductionBuild }

  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      All:

        sourceFilesTopDirectoryRelativePath: 01-Source/Pages

        partialsRecognition:
          excludeSubdirectoriesWithNames: [ Partials ]

        targetRuntime:
          type: BROWSER

        associatedMarkupEntryPointsGroupID_ForModulesDynamicLoadingWithoutDevelopmentServer: All
        buildingModeDependent:
          LOCAL_DEVELOPMENT: { outputTopDirectoryRelativePath: 02-LocalDevelopmentBuild }
          PRODUCTION: { outputTopDirectoryRelativePath: 03-ProductionBuild }
