common:

  $heading: "<code>$common</code> — общие настройки"

  secondsBetweenFileUpdatingAndStartingOfRebuilding:

    $heading: "<code>secondsBetweenFileUpdatingAndStartingOfRebuilding</code> — секунд между сохранением файла разметки и началом пересборки"
