common:

  $heading: "<code>$common</code> — Common Settings"

  secondsBetweenFileUpdatingAndStartingOfRebuilding:

    $heading: "<code>secondsBetweenFileUpdatingAndStartingOfRebuilding</code> — seconds between markup file saving and starting of rebuilding"
