top:

  $heading: `topPage.$heading`
  $URI: `topPage.$URI`

terminology:

  $heading: `terminology.$heading`
  $URI: `@All/Terminology/Terminology.${ fileNameLocalizationExtensions }`
  $sectioning:
    $specificationFileRelativePath: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.yaml
    $localizations:
      english: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.english.yaml
      japanese: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.japanese.yaml
      russian: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.russian.yaml

functionality:

  $heading: `functionality.$heading`

  $children:

    markupProcessing:

      $heading: `functionality.markupProcessing.$heading`

      $children:

        #        basicPugToHTML_Transpiling:
        #
        #          $heading: `functionality.markupProcessing.basicPugToHTML_Transpiling.$heading`
        #          $URI: `@All/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/BasicPugToHTML_Transpiling.${ fileNameLocalizationExtensions }`

        resourcesPointersResolving:

          $heading: `functionality.markupProcessing.resourcesPointersResolving.$heading`
          $URI: `@All/Functionality/MarkupProcessing/ResourcesPointersResolving/ResourcesPointersResolving.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.russian.yaml

# Functionality/MarkupProcessing/ResourcesPointersResolving/ResourcesPointersResolving.${ fileNameLocalizationExtensions }`

#configuration:
#
#  $heading: `configuration.$heading`
#
#  $children:
#
#    outputPackageJSON_Generating:
#
#      $heading: `configuration.outputPackageJSON_Generating.$heading`
#      $URI: `@All/Configuration/OutputPackageJSON_Generating/OutputPackageJSON_GeneratingConfiguration.${ fileNameLocalizationExtensions }`


configurationFile:

  $heading: Configuration File

  $children:

    commonSettings:

      $heading: `configuration.common.$heading`
      $URI: `@All/ConfigurationFile/Common/CommonSettings.${ fileNameLocalizationExtensions }`
      $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.yaml
      $localizations:
        english: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.english.yaml
        japanese: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.japanese.yaml
        russian: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.russian.yaml

    markupProcessing:

      $heading: `configuration.markupProcessing.$heading`
      $URI: `@All/ConfigurationFile/MarkupProcessing/MarkupProcessingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.russian.yaml

    stylesProcessing:

      $heading: `configuration.stylesProcessing.$heading`
      $URI: `@All/ConfigurationFile/StylesProcessing/StylesProcessingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.russian.yaml

    ECMAScriptLogicProcessing:

      $heading: ECMAScript Logic Processing
      $URI: https://github.com/TokugawaTakeshi/Yamato-Daiwa-Automation/blob/master/TemporaryDocumentation/API/ConfigurationFile/ECMA_ScriptProcessing/ECMA_ScriptProcessing.md

    plainCopying:

      $heading: Plain Copying
      $URI: https://github.com/TokugawaTakeshi/Yamato-Daiwa-Automation/blob/master/TemporaryDocumentation/API/ConfigurationFile/PlainCopying/PlainCopying.md

CLI:

  $heading: CLI
  $URI: https://github.com/TokugawaTakeshi/Yamato-Daiwa-Automation?tab=readme-ov-file#console
