top:

  $heading: `topPage.$heading`
  $URI: `topPage.$URI`

terminology:

  $heading: `terminology.$heading`
  $URI: `@All/Terminology/Terminology.${ fileNameLocalizationExtensions }`
  $sectioning:
    $specificationFileRelativePath: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.yaml
    $localizations:
      english: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.english.yaml
      japanese: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.japanese.yaml
      russian: 01-Source/Pages/Terminology/TableOfContents/Terminology.toc.russian.yaml

functionality:

  $heading: `functionality.$heading`

  $children:

    markupProcessing:

      $heading: `functionality.markupProcessing.$heading`

      $children:

        basicPugToHTML_Transpiling:

          $heading: `functionality.markupProcessing.basicPugToHTML_Transpiling.$heading`
          $URI: `@All/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/BasicPugToHTML_Transpiling.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/TableOfContents/BasicPugToHTML_Transpiling.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/TableOfContents/BasicPugToHTML_Transpiling.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/TableOfContents/BasicPugToHTML_Transpiling.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/BasicPugToHTML_Transpiling/TableOfContents/BasicPugToHTML_Transpiling.toc.russian.yaml

        HTML_Validation:

          $heading: `functionality.markupProcessing.HTML_Validation.$heading`
          $URI: `@All/Functionality/MarkupProcessing/HTML_Validation/HTML_Validation.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/HTML_Validation/TableOfContents/HTML_Validation.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/HTML_Validation/TableOfContents/HTML_Validation.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/HTML_Validation/TableOfContents/HTML_Validation.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/HTML_Validation/TableOfContents/HTML_Validation.toc.russian.yaml

        accessibilityChecking:

          $heading: `functionality.markupProcessing.accessibilityChecking.$heading`
          $URI: `@All/Functionality/MarkupProcessing/AccessibilityChecking/AccessibilityChecking.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/AccessibilityChecking/TableOfContents/AccessibilityChecking.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/AccessibilityChecking/TableOfContents/AccessibilityChecking.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/AccessibilityChecking/TableOfContents/AccessibilityChecking.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/AccessibilityChecking/TableOfContents/AccessibilityChecking.toc.russian.yaml

        resourcesPointersResolving:

          $heading: `functionality.markupProcessing.resourcesPointersResolving.$heading`
          $URI: `@All/Functionality/MarkupProcessing/ResourcesPointersResolving/ResourcesPointersResolving.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/ResourcesPointersResolving/TableOfContents/ResourcesPointersResolving.toc.russian.yaml

        importingFromTypeScript:

          $heading: `functionality.markupProcessing.importingFromTypeScript.$heading`
          $URI: `@All/Functionality/MarkupProcessing/ImportingFromTypeScript/ImportingFromTypeScript.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/ImportingFromTypeScript/TableOfContents/ImportingFromTypeScript.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/ImportingFromTypeScript/TableOfContents/ImportingFromTypeScript.toc.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/ImportingFromTypeScript/TableOfContents/ImportingFromTypeScript.toc.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/ImportingFromTypeScript/TableOfContents/ImportingFromTypeScript.toc.yaml

        localization:

          $heading: `functionality.markupProcessing.localization.$heading`
          $URI: `@All/Functionality/MarkupProcessing/Localization/Localization.${ fileNameLocalizationExtensions }`
          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Functionality/MarkupProcessing/Localization/TableOfContents/Localization.toc.yaml
            $localizations:
              english: 01-Source/Pages/Functionality/MarkupProcessing/Localization/TableOfContents/Localization.toc.english.yaml
              japanese: 01-Source/Pages/Functionality/MarkupProcessing/Localization/TableOfContents/Localization.toc.japanese.yaml
              russian: 01-Source/Pages/Functionality/MarkupProcessing/Localization/TableOfContents/Localization.toc.russian.yaml

        staticPreview:

          $heading: `functionality.markupProcessing.staticPreview.$heading`

          $children:

            stateDependentPagesVariations:
              $heading: `functionality.markupProcessing.staticPreview.stateDependentPagesVariations.$heading`
              $URI: `@All/Functionality/MarkupProcessing/StaticPreview/StateDependentPagesVariations/StateDependentPagesVariations.${ fileNameLocalizationExtensions }.pug`
              $localizations:
                english: 01-Source/Pages/Functionality/MarkupProcessing/StaticPreview/StateDependentPagesVariations/TableOfContents/StateDependentPagesVariations.toc.english.yaml
                japanese: 01-Source/Pages/Functionality/MarkupProcessing/StaticPreview/StateDependentPagesVariations/TableOfContents/StateDependentPagesVariations.toc.japanese.yaml
                russian: 01-Source/Pages/Functionality/MarkupProcessing/StaticPreview/StateDependentPagesVariations/TableOfContents/StateDependentPagesVariations.toc.russian.yaml

    browserLiveReloading:

      $heading: `functionality.browserLiveReloading.$heading`
      $URI: `@All/Functionality/BrowserLiveReloading/BrowserLiveReloading.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/Functionality/BrowserLiveReloading/TableOfContents/BrowserLiveReloading.toc.yaml
        $localizations:
          english: 01-Source/Pages/Functionality/BrowserLiveReloading/TableOfContents/BrowserLiveReloading.toc.english.yaml
          japanese: 01-Source/Pages/Functionality/BrowserLiveReloading/TableOfContents/BrowserLiveReloading.toc.japanese.yaml
          russian: 01-Source/Pages/Functionality/BrowserLiveReloading/TableOfContents/BrowserLiveReloading.toc.russian.yaml

    distributablePackageJSON_Generating:

      $heading: `functionality.distributablePackageJSON_Generating.$heading`
      $URI: `@All/Functionality/DistributablePackageJSON_Generating/DistributablePackageJSON_Generating.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/Functionality/DistributablePackageJSON_Generating/TableOfContents/DistributablePackageJSON_Generating.toc.yaml
        $localizations:
          english: 01-Source/Pages/Functionality/DistributablePackageJSON_Generating/TableOfContents/DistributablePackageJSON_Generating.toc.english.yaml
          japanese: 01-Source/Pages/Functionality/DistributablePackageJSON_Generating/TableOfContents/DistributablePackageJSON_Generating.toc.japanese.yaml
          russian: 01-Source/Pages/Functionality/DistributablePackageJSON_Generating/TableOfContents/DistributablePackageJSON_Generating.toc.russian.yaml

# Functionality/MarkupProcessing/ResourcesPointersResolving/ResourcesPointersResolving.${ fileNameLocalizationExtensions }`

#configuration:
#
#  $heading: `configuration.$heading`
#
#  $children:
#
#    distributablePackageJSON_Generating:
#
#      $heading: `configuration.distributablePackageJSON_Generating.$heading`
#      $URI: `@All/Configuration/distributablePackageJSON_Generating/distributablePackageJSON_GeneratingConfiguration.${ fileNameLocalizationExtensions }`


configurationFile:

  $heading: Configuration File

  $children:

    commonSettings:

      $heading: `configuration.common.$heading`
      $URI: `@All/ConfigurationFile/Common/CommonSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/Common/TableOfContents/CommonSettings.toc.russian.yaml

    markupProcessing:

      $heading: `configuration.markupProcessing.$heading`
      $URI: `@All/ConfigurationFile/MarkupProcessing/MarkupProcessingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/MarkupProcessing/TableOfContents/MarkupProcessingSettings.toc.russian.yaml

    stylesProcessing:

      $heading: `configuration.stylesProcessing.$heading`
      $URI: `@All/ConfigurationFile/StylesProcessing/StylesProcessingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/StylesProcessing/TableOfContents/StylesProcessingSettings.toc.russian.yaml

    ECMAScriptLogicProcessing:

      $heading: `configuration.ECMAScriptLogicProcessing.$heading`
      $URI: `@All/ConfigurationFile/ECMAScriptLogicProcessing/ECMAScriptLogicProcessing.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/ECMAScriptLogicProcessing/TableOfContents/ECMAScriptLogicProcessing.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/ECMAScriptLogicProcessing/TableOfContents/ECMAScriptLogicProcessing.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/ECMAScriptLogicProcessing/TableOfContents/ECMAScriptLogicProcessing.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/ECMAScriptLogicProcessing/TableOfContents/ECMAScriptLogicProcessing.toc.russian.yaml

    imagesProcessing:

      $heading: `configuration.imagesProcessing.$heading`
      $URI: `@All/ConfigurationFile/ImagesProcessing/ImagesProcessingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/ImagesProcessing/TableOfContents/ImagesProcessingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/ImagesProcessing/TableOfContents/ImagesProcessingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/ImagesProcessing/TableOfContents/ImagesProcessingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/ImagesProcessing/TableOfContents/ImagesProcessingSettings.toc.russian.yaml

    plainCopying:

      $heading: `configuration.plainCopying.$heading`
      $URI: https://github.com/TokugawaTakeshi/Yamato-Daiwa-Automation/blob/master/TemporaryDocumentation/API/ConfigurationFile/PlainCopying/PlainCopying.md

    browserLiveReloading:

      $heading: `configuration.browserLiveReloading.$heading`
      $URI: `@All/ConfigurationFile/BrowserLiveReloading/BrowserLiveReloadingSettings.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/ConfigurationFile/BrowserLiveReloading/TableOfContents/BrowserLiveReloadingSettings.toc.yaml
        $localizations:
          english: 01-Source/Pages/ConfigurationFile/BrowserLiveReloading/TableOfContents/BrowserLiveReloadingSettings.toc.english.yaml
          japanese: 01-Source/Pages/ConfigurationFile/BrowserLiveReloading/TableOfContents/BrowserLiveReloadingSettings.toc.japanese.yaml
          russian: 01-Source/Pages/ConfigurationFile/BrowserLiveReloading/TableOfContents/BrowserLiveReloadingSettings.toc.russian.yaml

consoleLineInterface:

  $heading: `consoleLineInterface.$heading`
  $URI: `@All/ConsoleLineInterface/ConsoleLineInterface.${ fileNameLocalizationExtensions }`
