projectBuilding:

  stylesProcessing:

    entryPointsGroups:

      StylesAndComponentsTesting:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Pages

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Build
          PRODUCTION:
            outputBaseDirectoryRelativePath: Build
